### ISSUE TITLE
Select Drop-down breaks on Microsoft Edge

### ISSUE THREAD

**Issue by akaustav** [StephenFluin/angular-update-guide#14]
### Overview
The [Angular Update Guide](https://update.angular.io/) breaks on Microsoft Edge 17.

### My Setup
- Windows 10 (April 2018 Update)
- Microsoft Edge 42.17134.1.0
- Microsoft EdgeHTML 17.17134

### Steps to reproduce
1. Open https://update.angular.io/ and wait for the page to load.
1. On the main form, click one of the dropdown controls to view the options list on the corresponding dropdown. For example, click the Package Manager dropdown.
1. Attempt to close the open dropdown menu of the corresponding dropdown. You can do this by either:
   - selecting the same value (as before) from the open menu.
   - selecting a different value from the open menu.
   - clicking outside the open menu area to close the menu and leave the old value selected on the field.
1. The page becomes un-responsive after this. The form doesn't respond any more. The `Show me how to update!` button can't be clicked either. Subsequent clicks anywhere on the page results in Edge displaying a notification saying `angular.io is not responding` with an option to `Recover webpage`.
![image](https://user-images.githubusercontent.com/11030959/39682990-dd5e5c24-5167-11e8-9687-42b8239eca3c.png)
1. After some-time the following error message shows on the browser console:
```
SCRIPT28: Out of stack space
from: polyfills.7de5477b8d4c2d9a397f.js (1,3217)
```

```
ERROR Error: Could not complete the operation due to error 80020101.

[object Error]: {
  description: "Could not complete the operation due to error 80020101.",
  message: "Could not complete the operation due to error 80020101.",
  number: -2147352319,
  stack: "Error: Could not complete the operation due to error 80020101.
    at it (https://update.angular.io/main.0f9a28351e902dd13d41.js:1:135267)
    at e.prototype.handleError (https://update.angular.io/main.0f9a28351e902dd13d41.js:1:135476)
    at Anonymous function (https://update.angular.io/main.0f9a28351e902dd13d41.js:1:151046)
    at t.prototype.invoke (https://update.angular.io/polyfills.7de5477b8d4c2d9a397f.js:1:7179)
    at e.prototype.run (https://update.angular.io/polyfills.7de5477b8d4c2d9a397f.js:1:2427)
    at e.prototype.runOutsideAngular (https://update.angular.io/main.0f9a28351e902dd13d41.js:1:141464)
    at e.prototype.tick (https://update.angular.io/main.0f9a28351e902dd13d41.js:1:151006)
    at Anonymous function (https://update.angular.io/main.0f9a28351e902dd13d41.js:1:149080)
    at t.prototype.invoke (https://update.angular.io/polyfills.7de5477b8d4c2d9a397f.js:1:7179)
    at onInvoke (https://update.angular.io/main.0f9a28351e902dd13d41.js:1:140439)"
}
```

### More Information
The problem is possibly originating from one (or a combination) of the following:
- the JavaScript engine in Edge 17,
- the Angular component code inside the `/src` folder of this repository, or
- the Angular version being used, or
- the Angular Material version or [Select Component](https://material.angular.io/components/select/overview) being used, or
- some other underlying library/component

**Comment by akaustav** [comment]
I tried testing on Edge 16. Same problem there too.
Although, I have waited for around 10 minutes, and I haven't receive the error on the browser console (step 5 from Steps to Reproduce).

Here is the setup of the machine where I tested:
Windows 10 Enterprise
Microsoft Edge 38.14393.2068.0
Microsoft EdgeHTML 14.14393

**Comment by akaustav** [comment]
@StephenFluin: Tested this today in Edge 17. Problem persists.
Has your fix been deployed yet?

**Comment by StephenFluin** [comment]
Hrm. The issue is fixed in dev mode (ng serve), but looks like it's still
there in production builds. Not sure what's going on. I'll look into it
more.

**Comment by lashtear** [comment]
Also tracking this on our end as 18447976, reproducible at least as early as RS3.

**Comment by StephenFluin** [comment]
@lashtear Do you have a link? I'd be curious to look at this together.

**Comment by lashtear** [comment]
Pretty sure that one isn't externally viewable, but: something is going awry with ng-animate or the polyfills being used on Edge.  It ends up in a recursive loop adding keyframe references to one of the divs (for animating the dropdown closing):

```html
<div class="ng-trigger ng-trigger-transformPanel ng-tns-c3-1 mat-select-panel mat-primary ng-star-inserted mat-select-panel-done-animating ng-animating" style="animation:gen_css_kf_1 150ms linear forwards, gen_css_kf_1 150ms linear forwards, gen_css_kf_1 150ms linear forwards,

gen_css_kf_2 350ms linear forwards, gen_css_kf_2 350ms linear forwards, gen_css_kf_2 350ms linear forwards, gen_css_kf_2 350ms linear forwards, gen_css_kf_2 350ms linear forwards, gen_css_kf_2 350ms linear forwards, gen_css_kf_2 350ms linear forwards, gen_css_kf_2 350ms linear forwards, gen_css_kf_2 350ms linear forwards, gen_css_kf_2 350ms linear forwards, ...
```

Linebreak added for clarity, and the list of gen_css_kf_2 points extends for hundreds of elements (as long as it runs).  Here's the js stack:

```text
...
e.prototype._flushDoneFns [Line: 8359, Col: 13], main.51cdd6d6f8572cd7e529.js
e.prototype.destroy [Line: 8355, Col: 13], main.51cdd6d6f8572cd7e529.js
e.prototype.destroy [Line: 8143, Col: 13], main.51cdd6d6f8572cd7e529.js
Anonymous function [Line: 7988, Col: 21], main.51cdd6d6f8572cd7e529.js
Anonymous function [Line: 8360, Col: 17], main.51cdd6d6f8572cd7e529.js
Array.prototype.foreEach
e.prototype._flushDoneFns [Line: 8359, Col: 13], main.51cdd6d6f8572cd7e529.js
e.prototype.destroy [Line: 8355, Col: 13], main.51cdd6d6f8572cd7e529.js
e.prototype.destroy [Line: 8143, Col: 13], main.51cdd6d6f8572cd7e529.js
Anonymous function [Line: 7988, Col: 21], main.51cdd6d6f8572cd7e529.js
Anonymous function [Line: 8360, Col: 17], main.51cdd6d6f8572cd7e529.js
Array.prototype.foreEach
e.prototype._flushDoneFns [Line: 8359, Col: 13], main.51cdd6d6f8572cd7e529.js
...
```

This repeats until chakra declares stack exhaustion.  Going to take a look at the non-prod setup to see what is different...

**Comment by lashtear** [comment]
As for prod vs dev mode-- it's the optimization step that seems to make a mess of it.  Turning that on but using sourcemaps gives us:

```text
…
e.prototype._flushDoneFns [Line: 4014, Col: 1], browser.js
e.prototype.destroy [Line: 4003, Col: 1], browser.js
e.prototype.destroy [Line: 3557, Col: 1], browser.js
Anonymous function [Line: 3322, Col: 1], browser.js
Anonymous function [Line: 4014, Col: 48], browser.js
Array.prototype.foreEach
e.prototype._flushDoneFns [Line: 4014, Col: 1], browser.js
...
```

**Comment by lashtear** [comment]
![screenshot of F12 inspection](https://i.imgur.com/5r4RZUu.png)

`buildOptimizer` seems to be the main difference; without the UglifyJS pass it works fine.  With that optimization, something changes that makes it loop when trying to dispose of the dropdown.

**Comment by lashtear** [comment]
Several more things are known; Chakra has the problem with or without JIT enabled.  Other browsers don't hit that loop.  Within the loop, it's doing the "right" thing, but nothing else encounters that loop.

Investigating the intersection of uglifyjs's minified output and ng-animate and the polyfills; this is looking delightfully weird.

**Comment by akaustav** [comment]
I do NOT observe this issue occurring any longer. However, I am on a different version of Windows 10 ([1809 - October 2018 Update](https://en.wikipedia.org/wiki/Windows_10_version_history#Version_1809_(October_2018_Update))) and therefore different version of MS Edge now.

- Microsoft Edge 44.17763.1.0
- Microsoft EdgeHTML 18.17763

Also, I have not been following up on the code changes to this repository - the components definitely look different now. Maybe a component modification/upgrade fixed this issue.

**Comment by akaustav** [comment]
I have access to another machine where this problem is NO longer reproducible. Here is the setup on that Windows 10 machine:
- Windows 10 (1709 - October, 2017 Update)
- Microsoft Edge 41.16299.1004.0
- Microsoft EdgeHTML 16.16299

I'll try to see if I have access to the same setup where I was originally able to reproduce this issue.

**Comment by akaustav** [comment]
I was able to get my hands on a laptop with the same setup as my original machine. I confirm that I am NO longer able to reproduce this issue.

The setup on which I tested is:

- Windows 10 (April 2018 Update)
- Microsoft Edge 42.17134.1.0
- Microsoft EdgeHTML 17.17134

Hence, I am closing this issue.
