### ISSUE TITLE
Migration to a version that is not latest

### ISSUE THREAD

**Issue by juristr** [StephenFluin/angular-update-guide#21]
The Update Guide currently discourages migration between multiple majors like v5 => v7, but rather v5 => v6 => v7.

However, when selectng v5 as starting point and v6 (which is not latest) as target, the instructions are still presented in a way that the latest versions would be installed. Like for the CLI package

```
npm install -g @angular/cli
npm install @angular/cli
ng update @angular/cli
```

It should rather be guarded, s.t. the `v6` of the package is installed.

(as a side-note, I'd also remove the instruction to install the `@angular/cli` as global package. It's not necessary for the upgrade to happen)

**Comment by brandoncash** [comment]
I'll be running through a 5.0 -> 6.1 update and will be happy to document the version numbers required.
Would a PR for this be welcomed? I unfortunately won't be covering all versions, but all but 6->7 are broken right now, and soon (~1 month) only 7->8 will be functional.

**Comment by StephenFluin** [comment]
@brandoncash yes, of course a PR would be welcome!

Basically all of the install and `ng update` commands have to be versioned (once a release is out of date), so that for example you are running `ng update @angular/cli@^7.0.0 @angular/core@^7.0.0` I believe.
