### ISSUE TITLE
update.angular.io should link to the repo

### ISSUE THREAD

**Issue by oBusk** [StephenFluin/angular-update-guide#22]
The upgrade guide should have a link to the repo to allow for people to have input. I'm not even sure if this repo is the actual source of `update.angular.io`. If there was a link to the repo on the page, there would be a clear, hard link.

Maybe a github style symbol in the top-bar to the right or in some kind of footer.

**Comment by Splaktar** [comment]
People seem to ask for the link where to submit issues/PRs on a monthly basis. It would be really helpful to have this repo linked from update.angular.io.

**Comment by mgechev** [comment]
We can consider moving to https://github.com/angular?
