### ISSUE TITLE
Updating 1 major and 1 minor release results in a warning about updating across multiple major versions

### ISSUE THREAD

**Issue by brandoncash** [StephenFluin/angular-update-guide#24]
The method to determine if an update spans multiple major versions is incorrectly identifying one major + one minor release as multiple major versions, resulting in the "We do not recommend moving across multiple major versions" warning.

Steps to reproduce:
- Select 5.0 as your beginning release.
- Select 6.0 as your target release.
- At this point, you have no error.
- Select 6.1 as your target release.
- You now have a warning about updating across multiple major versions, despite only moving one.

**Comment by chrisvelevitch** [comment]
I'm seeing the same problem with v6.1 -> v7.2

**Comment by fridoo** [comment]
You also see this message when selecting update v2.4 -> v4.0. Even though this a numerical move accross 2 major versions it technically isn't because there is no Angular v3 in between you could update to. So the warning probably shouldn't be displayed in this case.
