### ISSUE TITLE
Update for changes to Angular CLI 8.0.3 which require clean git status

### ISSUE THREAD

**Issue by Splaktar** [StephenFluin/angular-update-guide#35]
https://github.com/angular/angular-cli/issues/14589#issuecomment-504066707 makes a good point. With @clydin’s [change to require a clean `git` status](https://github.com/angular/angular-cli/commit/c96dd900d317993bd7431687e490818522b114df) before running `ng update`, the instructions here need to include at least a mention about committing files between runs of `ng update @angular/cli @angular/core` and `ng update @angular/material`.

Another option is to tell users about the `--allow-dirty` command which will let them otherwise follow this guide w/o issues.

**Comment by Splaktar** [comment]
For version 8 to version 9:

> - Run ng update @angular/core@8 @angular/cli@8 in your workspace directory to update to the latest 8.x version of @angular/core and @angular/cli and commit these changes.

> - Run ng update @angular/core @angular/cli --next. This step may require the --force flag if any of your third-party dependencies have not updated the Angular version of their peer dependencies.

> - Your project has now been updated to TypeScript 3.6, read more about new compiler checks and errors that might require you to fix issues in your code.

> - Run ng update @angular/material --next. This step may require the --force flag if any of your third-party dependencies have not updated the Angular version of their peer dependencies.

The first one mentions committing, the second doesn't, thus the 4th will fail due to a dirty workspace if the instructions are followed.

**Comment by Splaktar** [comment]
For [version 7 to version 8.2](https://update.angular.io/#7.0:8.2)

> - Update to version 8 of the core framework and CLI by running ng update @angular/cli @angular/core in your terminal

...

> - Update Angular Material to version 8 by running ng update @angular/material in your terminal.

There is no mention of the need to commit changes. So a user following the guide will see the update to `@angular/material` fail due to a dirty workspace.

**Comment by StephenFluin** [comment]
Fixed in f7c5581d5e610c22eb964cc7de359a09082ddee6
