### ISSUE TITLE
Wrong link to ::ng-deep

### ISSUE THREAD

**Issue by kubk** [StephenFluin/angular-update-guide#37]
URL: https://update.angular.io/#7.0:8.0
![image](https://user-images.githubusercontent.com/22447849/65854273-e03f7280-e364-11e9-9ba8-4abc4413d41f.png)

![image](https://user-images.githubusercontent.com/22447849/65854294-ed5c6180-e364-11e9-8b73-1ef573d4523b.png)

This recommendation should refer to [this page](https://angular.io/guide/component-styles), not [this](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html)

The link is correct in recommendation list: https://github.com/StephenFluin/angular-update-guide/blob/ca2753abbad878d231ec13f6f3e2cd9df41e71fb/src/app/recommendations.ts#L61

**Comment by Niladri24dutta** [comment]
@StephenFluin  if this is still open can  I work on this?

**Comment by Splaktar** [comment]
@Niladri24dutta yes, please submit a PR 😄

**Comment by Niladri24dutta** [comment]
> 
> 
> @Niladri24dutta yes, please submit a PR smile

Ok thanks. I am working on my fork.

**Comment by dkosasih** [comment]
This is fix with commit 6a008619aff46617159da40020b59feec4e8c61a.
Thanks @bitbruder .
