### ISSUE TITLE
Single quotes in npm install

### ISSUE THREAD

**Issue by Cyral** [StephenFluin/angular-update-guide#5]
This is a great tool and the suggested command saves a lot of time, but I'm not sure why there are quotes in it. With quotes the packages cannot be found.

`npm install @angular/animations@'^5.0.0' @angular/common@'^5.0.0' @angular/compiler@'^5.0.0' @angular/compiler-cli@'^5.0.0' @angular/core@'^5.0.0' @angular/forms@'^5.0.0' @angular/http@'^5.0.0' @angular/platform-browser@'^5.0.0' @angular/platform-browser-dynamic@'^5.0.0' @angular/platform-server@'^5.0.0' @angular/router@'^5.0.0' typescript@2.4.2 rxjs@'^5.5.2'`

**Comment by Cyral** [comment]
This was on Windows

**Comment by StephenFluin** [comment]
I believe this is fixed with the removal of most single quotes. Let me know if there are still issues.
