### ISSUE TITLE
Link to schematics or tslint rules that could help migrating

### ISSUE THREAD

**Issue by yjaaidi** [StephenFluin/angular-update-guide#51]
Would that make sense to add links to tools like Craig's tslint rule 
https://github.com/phenomnomnominal/angular-lazy-routes-fix to switch from route magic string `loadChildren: './admin/admin.module#AdminModule'` to async function `loadChildren: () => import('./admin/admin.module').then(m => m.AdminModule)`? 

Or maybe we be should just integrate this in the CLI update schematic 🤔?

**Comment by mgechev** [comment]
I believe we are already applying this migration automatically. Here's the [source code](https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/migrations/update-8/update-lazy-module-paths.ts) in the CLI repo.

**Comment by yjaaidi** [comment]
Thanks @mgechev! You are right. Shouldn't we remove the item below from the checklist? 

> For lazy loaded modules via the router, importing via string is deprecated. ng update will take care of this automatically. The new syntax leverages the ecosystem wide support for import rather than our custom rewrites. Your loadChildren route configs should be changed from a string such as loadChildren: './admin/admin.module#AdminModule' to an import statement such as loadChildren: () => import('./admin/admin.module').then(m => m.AdminModule). Learn more on angular.io.

**Comment by mgechev** [comment]
Looks correct to me:

>ng update will take care of this automatically.

**Comment by yjaaidi** [comment]
I agree but do we really need to mention it?
I feel like we have to shorten the update checklist as much as possible but I might be wrong 😅
Feel free to close if you don't agree.

**Comment by mgechev** [comment]
I believe our tech writer is currently looking at the guide. Let's close for now and revisit in future.
