### ISSUE TITLE
Update Guide not really work good

### ISSUE THREAD

**Issue by christophstockinger** [StephenFluin/angular-update-guide#57]
So I just tried to upgrade from version 7 to version 9 in my app. Unfortunately the guide here is just useless. The described steps are not really comprehensible and meaningful.
The following steps alone:

> Make sure you are using Node 10 or later.

> Make sure you are using Node 10.13 or later.

There are six more steps between the two. I also wonder if this guide really makes sense.

Maybe the maintainer should think about either improving the guide a lot so that it is useful or decide to stop the project and concentrate on other topics.

**Comment by mgechev** [comment]
That's the guide I see for the migration between 7 and 9, which seem pretty comprehensive. Do you see missing steps? Maybe the app doesn't visualize the steps properly for you? Would you provide a screenshot?

![update angular io_](https://user-images.githubusercontent.com/455023/76347482-f82c0280-62c3-11ea-9c15-a616c8bcda09.png)
